name: xUnit.net CI Build
on:
  push:
    branches:
      - main
      - 'rel/**'
  workflow_dispatch:

jobs:
  build:
    name: "CI Build"
    runs-on: ubuntu-22.04
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Clone source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Get .NET information
        run: dotnet --info

      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0

